[package]
name = "mercury_mqtt"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
serialport = {version = "4.3", default-features = false}
rumqttc = "0.25.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
env_logger = "0.11.11"
dotenv = "0.15"
chrono = "0.4"
anyhow = "1.0.103"
